version: '1'

services:
  db:
    container_name: redis
    image: redis:alpine
    command: redis-server
    ports:
     -  "6379:6379"
  
  go:
    container_name: chat-api
    build:
      context: ./backend
    ports:
      - 8080:8080
  ui:
    container_name: client-ui
    build:
     context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - /app
      - /app/node_modules
    
